### ISSUE TITLE
Request to sync lsm6dso-pid

### ISSUE THREAD

**Issue by StephS** [stm32duino/LSM6DSO#12]
I noticed that lsm6dso_reg doesn't have the this commit from https://github.com/STMicroelectronics/lsm6dso-pid/commit/2ddf91910ee3b4190940d4c138e0322e051f188f
Which fixes a typo and adds the timestamp_tag to lsm6dso_fifo_sensor_tag_get

**Comment by cparata** [comment]
Fix added in the main repo
