### ISSUE TITLE
[FR] Project Examples for PlatformIO Registry

### ISSUE THREAD

**Issue by JunjianChi** [stm32duino/LSM6DSO#14]
Hi,

Currently, the [library page](https://registry.platformio.org/libraries/stm32duino/STM32duino LSM6DSO) in the PlatformIO Registry doesn't contain any quick start projects for developers. Such examples serve both to highlight widespread use cases and to help newcomers to get up and running much more quickly.

Please consider adding a few comprehensive project examples to the PlatformIO Registry.

Useful links:
- https://registry.platformio.org/libraries/stm32duino/STM32duino LSM6DSO
- https://docs.platformio.org/en/latest/manifests/library-json/fields/examples.html

**Comment by cparata** [comment]
Hi @JunjianChi ,
you can download the release v2.2.0 that contains some examples.
Best Regards,
Carlo
