### ISSUE TITLE
Ask for example code

### ISSUE THREAD

**Issue by haoen0116** [stm32duino/LSM6DSO#8]
Hello, could author provide the example code which can get accelerometer and gyroscope data?

**Comment by cparata** [comment]
Hi @haoen0116 ,
you can give a look at the examples contained in the X-NUCLEO-IKS01A3 library for LSM6DSO [here](https://github.com/stm32duino/X-NUCLEO-IKS01A3/tree/master/examples). They can be easily adapted to all LSM6DSO boards.
In particular to understand how to read acc and gyro data, you can give a look at [X_NUCLEO_IKS01A3_Hello_World.ino](https://github.com/stm32duino/X-NUCLEO-IKS01A3/blob/master/examples/X_NUCLEO_IKS01A3_HelloWorld/X_NUCLEO_IKS01A3_HelloWorld.ino) obviously extracting only the part regarding LSM6DSO. Let me know if you have any issue.
Best Regards,
Carlo

**Comment by fpistm** [comment]
`README.md` also provides the minimal codes to use it.
As OP does not provide any feedback, assume it is OK.
